### ISSUE TITLE
Issues building

### ISSUE THREAD

**Issue by ftclausen** [blackboard/protractor-sync#77] opened 2018-09-25 05:20 UTC
The latest develop seems to fail with

```
$ grunt build
Running "clean:build" (clean) task
>> 1 path cleaned.

Running "ts:build" (ts) task
Compiling...
Using the custom compiler : node_modules/typescript/bin/tsc
node_modules/@types/selenium-webdriver/remote.d.ts(139,29): error TS2304: Cannot find name 'Map'.
app/browser-sync.ts(146,10): error TS2346: Supplied parameters do not match any signature of call target.

>> 2 non-emit-preventing type warnings
>> Error: tsc return code: 2
Warning: Task "ts:build" failed. Use --force to continue.

Aborted due to warnings.
```

I'm using Node 8.6.0 - not quite sure how to fix that one.

**Comment by scriby** [comment] 2018-09-25 06:36
I think you must have installed dependencies using "npm install" instead of "yarn".

It looks like some of the underlying dependencies upgraded which caused the build issue. If you install with yarn it'll grab the versions of the deps in the yarn lockfile and still build properly.

**Comment by scriby** [comment] 2018-09-25 06:43
Hmm, I just noticed that the yarn.lock file is not checked in!

Are you all using "yarn" or "npm install" to install on the build server & for development? The corresponding lock file for whichever is being used should be checked in to make sure the build is reproducible and won't randomly break.

**Comment by ftclausen** [comment] 2018-09-25 11:08
Thanks for your prompt response! I was using ‘npm install’ so I’ll be sure to use yarn instead.

**Comment by scriby** [comment] 2018-09-25 15:02
Actually I think both will fail from a clean directory. I just had an old yarn.lock file leftover which is why mine worked.

**Closed as completed** 2018-09-26 05:23 UTC
